name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4', '3.5']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop

    - uses: qltysh/qlty-action/coverage@v2
      if: matrix.ruby == '3.5'
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: coverage/.resultset.json
